create table if not exists public.visits (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone not null default now(),
  page text,
  referrer text,
  user_agent text
);

alter table public.visits enable row level security;

drop policy if exists "Allow anonymous visit inserts" on public.visits;

create policy "Allow anonymous visit inserts"
on public.visits
for insert
to anon
with check (true);

grant insert on table public.visits to anon;
grant usage, select on sequence public.visits_id_seq to anon;

create or replace function public.get_visit_count()
returns bigint
language sql
stable
security definer
set search_path = public
as $$
  select count(*) from public.visits;
$$;

grant execute on function public.get_visit_count() to anon;
